### ISSUE TITLE
Init Error

### ISSUE THREAD

**Issue by urus1369** [prestonkelly/Mastermind#6]
Hey there,

  Trying to give your app a run to learn and, ofc, use it. I'm running into this issue though:

```
Traceback (most recent call last):
  File "app.py", line 1153, in <module>
    root.iconbitmap(default='favicon.ico')
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1869, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"
```

 whenever I try to init the app. Any ideas on how to sort this? Thank you!

**Comment by urus1369** [comment]
ok... got that to work, now Tkinter is throwing another error when trying to actually display the main window:

```
File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "app.py", line 61, in <lambda>
    command=lambda: [self.add_keys(), self.new_window()])
  File "app.py", line 98, in new_window
    bb = MainApplication(self.newWindow)
  File "app.py", line 1004, in __init__
    self.controls = Controls(self)
  File "app.py", line 313, in __init__
    self.main_listbox.insert(tk.END, f[i])
IndexError: list index out of range
```

**Comment by prestonkelly** [comment]
Hi @urus1369, 

I just pulled the code down and I'm receiving the same thing. I haven't worked on this project as you can tell, in a very long time (python 3.7.7) lol. One thing to keep in mind, make sure to set the api keys otherwise the app will have no idea what data to load. At the time, my error handling skills were not the best and I guess I let users sign into the app without having to input their apis keys. It looks like the error could be caused by the api not connecting correctly. Unfortunately, Binance no longer allows US users to use their site since Binance.US is a thing now and I'm unable to check whether this would work with proper api keys. Let me know if you solved this, I'd love to hear what the solution was.

**Comment by urus1369** [comment]
Hi Preston,

  Yeah... so even with the API keys correctly inputted into the initial dialogue the app spits out the same error. From the looks of it, the erros are related to the Tkinter library handling the GUI. Are u still interesting in doing a GUI trading-station-like project? Or was this a one-off for u
